# Generated by Django 6.0 on 2025-12-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_recruiterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
