# Generated by Django 6.0 on 2025-12-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_recruiterprofile_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
